version: '3.4'

services: 

    php-7.4:
      image: php-7.4
      container_name: myphp-7.4
      build: .
      volumes:
          - ./src:/var/www/html
          - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      ports: 
          - 808:80 # apache

      command: bash -c "/etc/init.d/apache2 start && tail -f /dev/null" # start apache && open conatiner